export const langMap: Record<string, string> = {
  "Dutch Flemish": "nl",
  "Abkhaz": "ab",
  "Afar": "aa",
  "Afrikaans": "af",
  "Albanian": "sq",
  "Amharic": "am",
  "Arabic": "ar",
  "Armenian": "hy",
  "Assamese": "as",
  "Avar": "av",
  "Aymara": "ay",
  "Azerbaijani": "az",
  "Bambara": "bm",
  "Bashkir": "ba",
  "Basque": "eu",
  "Belarusian": "be",
  "Bhojpuri": "bh",
  "Bosnian": "bs",
  "Breton": "br",
  "Bulgarian": "bg",
  "Catalan": "ca",
  "Chamorro": "ch",
  "Chechen": "ce",
  "Chinese (Simplified)": "zh",
  "Chinese (Traditional)": "zh",
  "Chuvash": "cv",
  "Corsican": "co",
  "Croatian": "hr",
  "Czech": "cs",
  "Danish": "da",
  "Dutch": "nl",
  "Dzongkha": "dz",
  "English": "en",
  "Esperanto": "eo",
  "Estonian": "et",
  "Ewe": "ee",
  "Faroese": "fo",
  "Fijian": "fj",
  "Filipino": "tl",
  "Finnish": "fi",
  "French": "fr",
  "French (Canada)": "fr",
  "Frisian": "fy",
  "Ga": "bg",
  "Galician": "gl",
  "Georgian": "ka",
  "German": "de",
  "Greek": "el",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Haitian Creole": "ht",
  "Hausa": "ha",
  "Hebrew": "he",
  "Hindi": "hi",
  "Hungarian": "hu",
  "Icelandic": "is",
  "Igbo": "ig",
  "Indonesian": "id",
  "Irish": "ga",
  "Italian": "it",
  "Japanese": "ja",
  "Javanese": "jv",
  "Kalaallisut": "kl",
  "Kannada": "kn",
  "Kanuri": "kr",
  "Kazakh": "kk",
  "Khmer": "km",
  "Kinyarwanda": "rw",
  "Komi": "kv",
  "Korean": "ko",
  "Kurdish (Kurmanji)": "ku",
  "Kurdish (Sorani)": "ku",
  "Kyrgyz": "ky",
  "Lao": "lo",
  "Latin": "la",
  "Latvian": "lv",
  "Limburgish": "li",
  "Lingala": "ln",
  "Lithuanian": "lt",
  "Luxembourgish": "lb",
  "Macedonian": "mk",
  "Malagasy": "mg",
  "Malay": "ml",
  "Malay (Jawi)": "ml",
  "Malayalam": "ml",
  "Maltese": "mt",
  "Manx": "gv",
  "Marathi": "mr",
  "Marshallese": "mh",
  "Mongolian": "mn",
  "Ndebele (South)": "nd",
  "Nepali": "ne",
  "Norwegian": "nb",
  "Occitan": "oc",
  "Odia (Oriya)": "or",
  "Oromo": "om",
  "Pashto": "ps",
  "Persian": "fa",
  "Polish": "pl",
  "Portuguese (Brazil)": "pt",
  "Portuguese (Portugal)": "pt",
  "Punjabi (Gurmukhi)": "pa",
  "Punjabi (Shahmukhi)": "pa",
  "Quechua": "qu",
  "Romani": "mo",
  "Romanian": "mo",
  "Rundi": "rn",
  "Russian": "ru",
  "Sami (North)": "se",
  "Samoan": "sm",
  "Sango": "sg",
  "Sanskrit": "sa",
  "Serbian": "sh",
  "Shona": "sn",
  "Sindhi": "sd",
  "Sinhala": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Somali": "so",
  "Spanish": "es",
  "Sundanese": "su",
  "Swahili": "sw",
  "Swati": "ss",
  "Swedish": "sv",
  "Tahitian": "ty",
  "Tajik": "tg",
  "Tamil": "ta",
  "Tatar": "tt",
  "Telugu": "te",
  "Thai": "th",
  "Tibetan": "bo",
  "Tigrinya": "ti",
  "Tongan": "to",
  "Tsonga": "ts",
  "Tswana": "tn",
  "Turkish": "tr",
  "Turkmen": "tk",
  "Ukrainian": "uk",
  "Urdu": "ur",
  "Uyghur": "ug",
  "Uzbek": "uz",
  "Venda": "ve",
  "Vietnamese": "vi",
  "Welsh": "cy",
  "Wolof": "wo",
  "Xhosa": "xh",
  "Yiddish": "ji",
  "Yoruba": "yo",
  "Zulu": "zu"
};